create table if not exists accounts (
    id bigint generated by default as identity primary key,
    email varchar(320) not null unique,
    password varchar(255) not null,
    status varchar(20) not null,
    user_role varchar(20) not null,
    social_provider varchar(20) not null default 'LOCAL',
    provider_user_id varchar(128),
    profile_image_url varchar(1024),
    created_at timestamp not null default current_timestamp,
    last_login_at timestamp null,
    login_fail_count integer not null default 0
);

create unique index if not exists uk_social_provider_user_id
    on accounts(social_provider, provider_user_id);
